cart/urls.py
from django.urls import re_path
from . import views


urlpatterns = [
    re_path(r'^$', views.cart_detail, name='cart_detail'),
    re_path(r'^add/(?P<product_id>\d+)/$', views.add_to_cart, name='add_to_cart'),
    re_path(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

django_my_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('shop/', include(('shop.urls', 'shop'), namespace='shop')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('', home, name='home')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path("", home, name='home'),
    path('detail/<int:product_id>/<str:product_slug>/', product_detail, name='product_detail'),
    path('category/<str:slug>/', product_list_by_category, name='product_list_by_category'),
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse
from multiselectfield import MultiSelectField


class Category(models.Model):
    """Класс, описывающий модель категории"""
    name = models.CharField(max_length=200, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


def get_upload_path(category, filename):
    return f'{category.name}/{filename}'


class Product(models.Model):
    """Класс, описывающий модель отдельного продукта"""
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE, verbose_name='Категория')
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.FileField(blank=True, upload_to=get_upload_path, verbose_name='Изображения')

    # image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, verbose_name='Изображение')

    SIZE_CHOICES = (('XXS', 'XXS'),
                    ('XS', 'XS'),
                    ('S', 'S'),
                    ('M', 'M'),
                    ('XL', 'XL'),
                    ('XXL', 'XXL'))

    sizes = MultiSelectField(choices=SIZE_CHOICES,
                             max_choices=6,
                             max_length=17)

    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    stock = models.PositiveIntegerField(verbose_name='Остаток')
    available = models.BooleanField(default=True, verbose_name='Доступен')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товары'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])


# def get_upload_path(instance, filename):
#     model = instance.album.model.__class__._meta
#     name = model.verbose_name_plural.replace(' ', '_')
#     return f'{name}/images/{filename}'


class ProductImage(models.Model):
    """Класс для хранения нескольких фото продукта"""
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE, verbose_name='Товар')
    images = models.FileField(upload_to=get_upload_path, verbose_name='Изображения')

    def __str__(self):
        return self.product.name

# class Size(models.Model):
#     """Класс, описывающий доступные размеры каждого товара"""
#     product = models.ForeignKey(Product, related_name='products', on_delete=models.CASCADE, verbose_name='Товар')
#     sizes = models.CharField(choices=sizes)

cart/forms.py
from django import forms
from django.forms import ModelForm
from shop.models import Product


class CartAddProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['sizes']

    def __init__(self, pk, *args, **kwargs):
        super(CartAddProductForm, self).__init__(*args, **kwargs)
        sizes = tuple(Product.objects.get(pk=pk).sizes)
        sizes_list = []
        for item in sizes:
            sizes_list.append((item, item))
        self.fields['sizes'] = forms.ChoiceField(choices=sizes_list)

cart/views.py
from django.core.handlers.wsgi import WSGIRequest
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def add_to_cart(request: WSGIRequest, product_id: int) -> HttpResponseRedirect:
    """Добавляет товары в корзину"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request: WSGIRequest, product_id: int) -> HttpResponseRedirect:
    """Удаляет товары из корзины"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request: WSGIRequest) -> HttpResponse:
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                     'update': True})
    # coupon_apply_form = CouponApplyForm()
    return render(request,
                  'cart/detail.html',
                  {'cart': cart,
                   # 'coupon_apply_form': coupon_apply_form
                   })

django_my_shop/views.py
from django.http import HttpResponse
from django.shortcuts import render
from shop.models import *
from django.core.handlers.wsgi import WSGIRequest


def home(request: WSGIRequest) -> HttpResponse:
    """Главная страница сайта"""
    categories = Category.objects.all()
    products = Product.objects.all()
    return render(request, 'main.html', {'categories': categories,
                                         'products': products})

shop/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from .models import *
from django.core.handlers.wsgi import WSGIRequest
from typing import Union
from cart.forms import *


def home(request: WSGIRequest) -> HttpResponse:
    """Главная страница магазина"""
    products = Product.objects.all()
    return render(request, 'shop/home.html', {'products': products})


def product_detail(request: WSGIRequest, product_id: int, product_slug: str) -> HttpResponse:
    """Функция отображения конкретного товара"""
    product = get_object_or_404(Product,
                                id=product_id,
                                slug=product_slug,
                                available=True)
    pk = product.pk
    categories = Category.objects.all()
    cart_product_form = CartAddProductForm(instance=product, pk=pk)
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'categories': categories,
                                                        'cart_product_form': cart_product_form})


def product_list_by_category(request: WSGIRequest, slug: str) -> HttpResponse:
    """Функция отображения всех доступных товаров"""
    category = get_object_or_404(Category, slug=slug)
    categories = Category.objects.all()
    products = Product.objects.filter(category=category, available=True)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})

templates/main.html
{% extends "shop/base.html" %}
<head>
    <meta charset="UTF-8">
    <title>Main Page</title>
</head>
<body>
{% block content %}
    <br>Наши товары:
    {% for product in products %}
        <div class="item">
            <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}" width="300" height="500"> <br>
            </a>
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
            {{ product.price }} <br>
            Доступные размеры: <br>
            {{ product.sizes }}<br>
        </div>
    {% endfor %}
{% endblock %}
</body>

templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
Категории товаров:
{% for c in categories %}
    <li {% if category.slug == c.slug %} class="selected"{% endif %}>
        <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
    </li>
{%  endfor %}

<a href="#">Регистрация</a>
<a href="#">Войти</a>

{% block content %}
{% endblock %}

</body>
</html>

templates/shop/home.html
{% extends "shop/base.html" %}
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
{% block content %}
    {% for product in products %}
        <div class="item">
            <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}">
            </a>
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
            {{ product.price }}
        </div>
    {% endfor %}
{% endblock %}
</body>

templates/shop/product/detail.html
{% extends "shop/base.html" %}
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
{% block content %}
    <br>
    <b>{{ product.name }} </b> <br>
    <i>{{ product.description }} </i> <br>
    {{ product.price }} <br>
    <img src="{{ product.image.url }}" width="300" height="500"> <br>
    Доступные размеры: <br>
    {{ product.sizes }}<br>
    <form action="{% url "cart:add_to_cart" product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Добавить в корзину">
    </form>
{% endblock %}
</body>

templates/shop/product/list.html
{% extends "shop/base.html" %}
<head>
    <meta charset="UTF-8">
    <title>List</title>
</head>
<body>
{% block content %}
    <br>
    Товары категории {{ category.name }}:<br>
    {% for p in products %}
        <a href="{{ p.get_absolute_url }}">
            <img src="{{ p.image.url }}" width="300" height="500">
        </a> <br>
        <a href="{{ p.get_absolute_url }}">{{ p.name }}</a><br>
        {{ p.price }}<br>
        Доступные размеры: <br>
        {{ p.sizes }}<br>
    {% endfor %}
{% endblock %}
</body>